### ISSUE TITLE
Widget is hanging without success

### ISSUE THREAD

**Issue by lijinbio** [vitessce/vitessce-python#124]
Hi all,

I am visualizing 8,000 cells of 20,000 genes via vitessce-python. The data seems to be able to load successfully, but the widget windows are hanging there forever. Like,

<img width="1090" alt="Screen Shot 2022-03-23 at 12 59 25 AM" src="https://user-images.githubusercontent.com/16247242/159634058-e0717371-39ef-47b9-959c-3b04bbc08077.png">

There is no error message in the notebook. Could you please help suggest how to run vitessce-python correctly? Thanks.

**Comment by keller-mark** [comment]
Can you shift-click in the notebook and click Inspect to open the browser console, and send the output? There might be a message there that would help to debug.

https://jupyterlab.readthedocs.io/en/stable/user/interface.html#context-menus

**Comment by lijinbio** [comment]
Hi @keller-mark , thank you so much for your suggestion. Yes, I saw the error message in the console. I don't quite understand how to fix it. Could you please help suggest what could be a problem and how could I fix the error? Thank you so much.

<img width="1672" alt="Screen Shot 2022-03-23 at 8 27 18 AM" src="https://user-images.githubusercontent.com/16247242/159710321-45605a61-f392-4f0d-bc15-06d85120a30a.png">

**Comment by keller-mark** [comment]
Hi @lijinbio, it looks like it could have something to do with the data type for the `subtype` column in the `obs` data frame.

Assuming the AnnData object is stored in the variable `adata`, what is the output of `adata.obs['subtype'].values.dtype` ?

**Comment by lijinbio** [comment]
Hi @keller-mark , the data type of the subtype column is categorical. Say,

```
>>> import scanpy as sc
>>> x=sc.read('merfish_impute_outer_merfish_wt2_JC_5.h5ad')
>>> x.obs.info()
<class 'pandas.core.frame.DataFrame'>
Index: 8854 entries, 3537-1 to 727533-1
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype   
---  ------                   --------------  -----   
 0   sampleid                 8854 non-null   category
 1   assigned_transcripts     8854 non-null   float64 
 2   center_x                 8854 non-null   float64 
 3   center_y                 8854 non-null   float64 
 4   region                   8854 non-null   int64   
 5   batch                    8854 non-null   category
 6   rna_count_based_density  8854 non-null   float32 
 7   uniform_density          8854 non-null   float64 
 8   volume                   8854 non-null   float64 
 9   majortype                8854 non-null   category
 10  subtype                  8854 non-null   category
 11  n_counts                 8854 non-null   float32 
dtypes: category(4), float32(2), float64(5), int64(1)
memory usage: 851.4+ KB
>>> x.obs['subtype'].values.dtype
CategoricalDtype(categories=['1_W3D1.1', '2_W3D1.2', '3_FminiON', '4_FminiOFF', '5_J-RGC',
                  '6_W3B', '7_Novel', '8_Novel', '9_Tbr1_Novel', '10_Novel',
                  ...
                  'BC6', 'BC7', 'BC8', 'BC9', 'Cone', 'HC', 'MG', 'RBC', 'Rod',
                  'Unknown'],
, ordered=False)
```

May I ask if vitessce-python requires a certain type for a metadata column? Thanks.

**Comment by lijinbio** [comment]
Hi @keller-mark , thank you for the suggestion. I have converted the categorical metadata to objects, but I still saw the two errors without finding "subtype" and "majortype" from the object.

![Screen Shot 2022-03-23 at 1 27 29 PM](https://user-images.githubusercontent.com/16247242/159770678-67f59b15-4388-4368-a698-3d8aa3729eb7.png)

Could you please help suggest why the two columns are still not correctly loaded? Thank you so much for your help.

**Comment by lijinbio** [comment]
Hi @keller-mark, I have also tried the example in the repository, say,
https://github.com/vitessce/vitessce-python/blob/master/docs/notebooks/widget_pbmc.ipynb

However, Vitessce didn't run successfully either.

<img width="1840" alt="Screen Shot 2022-03-27 at 1 32 00 PM" src="https://user-images.githubusercontent.com/16247242/160295508-741f5da9-4292-491f-9fe8-a4b2e5a22542.png">

Could you please help suggest how could I run vitessce correctly? Thanks.

**Comment by keller-mark** [comment]
Thanks for bringing this to our attention. I did not realize, but it seems that newer AnnData versions (0.8.0 and later) save categorical arrays in AnnData objects differently than 0.7.8 and earlier. 

We will need to work on supporting those newer AnnData objects in the package (I will make some new GitHub issues for our internal development), but for now one solution would be to downgrade the `anndata` package to version `0.7.8` in your python environment.

References:
- https://anndata.readthedocs.io/en/latest/release-notes/index.html
- https://github.com/theislab/anndata/pull/554
- https://github.com/theislab/anndata/commit/664e32b0aa6625fe593370d37174384c05abfd4e#diff-378289cd041549952bec58a380676d03830a6a8e99b8cccd24295a797cffd385

**Comment by lijinbio** [comment]
Yes, downgrading anndata to 0.7.8 works. Thanks for the quick solution.
