### ISSUE TITLE
Why is `NPM_AUTH_TOKEN` needed for in `test.yml`?

### ISSUE THREAD

**Issue by mccalluc** [vitessce/vitessce-python#132]
It shouldn't require any secrets to run tests, and the tests certainly shouldn't be pushing anything upstream, so what is `NPM_AUTH_TOKEN` needed for in `test.yml`? I may start a branch with those removed to see if it still works.

**Comment by keller-mark** [comment]
I am not sure, if removing them works then go for it. If it is not required, then I must have just copied the `npm publish` section from the `deploy.yml` before modifying it `https://github.com/vitessce/vitessce-python/blob/master/.github/workflows/deploy.yml#L75` and forgot to remove that line from the section.
