### ISSUE TITLE
Use one version number for both PyPI and NPM

### ISSUE THREAD

**Issue by keller-mark** [vitessce/vitessce-python#172]
In `vitessce/_version.py` read the version from `js/package.json`. Bump the current version in package.json to be greater than `max(current pypi, current npm)`

Update the Deployment section of README.md to note that bumping the PyPI package version will require running `npm version`.

**Comment by mccalluc** [comment]
There's also a reference in [vitessce/config.py](https://github.com/vitessce/vitessce-python/pull/174/files#diff-6db27fb59b7b7095c326b203ca67c360f32641a91da27f7d3fd6fff335f54dbd), in a default kwarg. Not sure about the best solution.

**Comment by keller-mark** [comment]
That is a schema version, which does not (at least currently) align with any package version
