### ISSUE TITLE
upgrade vitessce version?

### ISSUE THREAD

**Issue by tmchartrand** [vitessce/vitessce-python#209]
I'm hoping that the pinned version of the core vitessce.js dependency can be updated sometime soon? In particular, this is because of the newer Anndata support (https://github.com/vitessce/vitessce/pull/1319), but in general it seems that development of the core library is more active, so I'm curious how regularly to expect the version to get bumped up in vitessce-python.
Thanks!

**Comment by ilan-gold** [comment]
I think I may take this on soon.  I need to take care of something else in this repo anyway.

**Comment by lee-t** [comment]
Also hoping to see vitessce-python bumped up soon.  The affects from the js refactor in the core Vitessce not only brings in new features but hopefully will fix a longstanding issue we've had with html widgets after conversion with nbconvert (#206, #208)

**Comment by ilan-gold** [comment]
We're dealing with some bugs right now from the release that side tracked me a bit.  They should be handled now so this is next.  Will probably handle this tomorrow or Monday.  Sorry for the delay.  First we will upgrade to the last 1.X.X version and then to 2.0.X which will have even better Jupyter integration.

**Comment by ilan-gold** [comment]
Coming now.
