### ISSUE TITLE
Simplify AnnDataWrapper class by using zarr-based AnnData

### ISSUE THREAD

**Issue by keller-mark** [vitessce/vitessce-python#23]
Now that we have AnnData-Zarr loaders directly in Vitessce, we should be able to both simplify the code here and achieve better performance (I think) https://github.com/vitessce/vitessce/pull/807

We should use the `.write_zarr` function

**Comment by keller-mark** [comment]
We probably need to refactor the data wrapper classes so that many view config file definitions can be created while only a single file / directory is served

**Comment by ilan-gold** [comment]
@keller-mark Could you make that a bit clearer? I made a "multi-file" config in #32 but feel like I don't know quite know what I am doing.  If you want to review there to make your ideas clear that's ok.

**Comment by keller-mark** [comment]
That looks fine, I am referring more specifically to this loop https://github.com/vitessce/vitessce-python/blob/07a2721/vitessce/routes.py#L20 over data types: the loop assumes that for a specific data wrapper object `obj`, the `obj._get_data` function for a particular data type such as `cells` will return both:
- `dt_obj_file_defs` like
   ```json
      [
            {
                  "url": "http://localhost:4000/my-anndata.zarr",
                  "fileType": "anndata-cells.zarr",
                  "type": "cells"
            }
       ]
    ```
- `dt_obj_routes` which is a list of starlette Routes like
    ```python
      [
            Mount(self._get_route(dataset_uid, obj_i, "cells"),
                    app=StaticFiles(directory=os.path.dirname(zarr_filepath), html=False, check_dir=False)),
       ]
    ```

but for the AnnData data types, we can get multiple data types out of the same anndata Zarr store ("cells", "expression-matrix", "cell-sets"), so if the loop iteration gets to "cell-sets" the route will return different `dt_obj_file_defs` but will try to mount the same Zarr directory again. I am not actually sure if serving the same zarr store twice on two different routes will cause any issues but I figured there is a possibility

**Comment by ilan-gold** [comment]
@keller-mark That makes sense ok.  Thanks for explaining.

**Comment by keller-mark** [comment]
Done in #39
