### ISSUE TITLE
Failed to load model class "Anymodel"

### ISSUE THREAD

**Issue by CReihsmann** [vitessce/vitessce-python#305]
I'm trying to run vitessce in jupyter notebooks. Tried running mine and the tutorial example (both on a mac and pc) but everytime I try to run vc.widget() it gives error saying `Failed to load model class 'AnyModel' from module 'anywidget' /n Error: Script error for "anywidget"`

**Comment by keller-mark** [comment]
Hi, thanks for the issue. Can you please try the solutions mentioned in this comment https://github.com/higlass/higlass-python/issues/133#issuecomment-1692079494 and in the troubleshooting section here https://github.com/vitessce/vitessce-python#troubleshooting

In particular, can you share the version of python that you are using and the output of `conda list` or `pip list` for the environment?

**Comment by CReihsmann** [comment]
The first link provided solved the issue. Looks like anywidget was installed in my working environment but not the base environment I used to open jupyter notebooks. Thanks!
