### ISSUE TITLE
ValueError: data too large for non-BigTIFF file

### ISSUE THREAD

**Issue by J-Yash** [vitessce/vitessce-python#318]
Hi,
I am trying to save a numpy array (RGB image of an H&E histology slide; dtype=uint8) as an ome.tif file using multiplex_img_to_ome_tiff(). The array is a little over 4 GB (based on the original image file). Does Vitessce not support ome.tif files over 4GB? How can I display files over that size? (Note: I tried downsampling the array by a factor of 2 and everything worked fine.)

Thanks!

**Comment by keller-mark** [comment]
Ah thanks for reporting this @J-Yash , we probably need to add a parameter to tell the `tifffile` library to use the BigTiff format

**Comment by J-Yash** [comment]
Got it @keller-mark. I didn't try it but assume rgb_img_to_ome_tiff() would have a similar issue. I'll work with downscaled images in the meantime!

**Comment by keller-mark** [comment]
Another workaround for now would be to use the tifffile code within those functions directly https://github.com/vitessce/vitessce-python/blob/83b1411f170a96394e6e5e05f5970ca1c0e0dd0c/vitessce/data_utils/ome.py#L41 and manually add the `bigtiff=True` parameter

**Comment by J-Yash** [comment]
Thanks @keller-mark. This works!
