### ISSUE TITLE
Vitessce python on remote jupyter servers do not work

### ISSUE THREAD

**Issue by edwin5588** [vitessce/vitessce-python#358]
- Vitessce visualizer on remote servers do not work, it outputs a semi-functional visualization with 0 cells detected. It seems to not be able to find the files hosted on the remote Jupyter server
- The bug can be replicated using vitessce's Binder example: https://mybinder.org/v2/gh/vitessce/vitessce-python/main?filepath=docs/notebooks/widget_pbmc.ipynb
- If you execute all cells until the end, you'll see the visualizer pop out but with 0 cells detected.

**Comment by edwin5588** [comment]
@keller-mark Just tagging one of the devs to hopefully get some eyes on this issue. Thanks!

**Comment by keller-mark** [comment]
<img width="1421" alt="Screenshot 2024-09-11 at 2 19 17 PM" src="https://github.com/user-attachments/assets/ede1ef1e-1022-45f2-b691-a149fc9d497e">

Hi @edwin5588 it seems like binder may have updated such that the `proxy=True` no longer works to allow remote access to the served files (https://python-docs.vitessce.io/data_options.html for background).

As a workaround, I have made a pull request at https://github.com/vitessce/vitessce-python/pull/363 that uses the `adata_store` functionality to allow access to AnnData objects via Zarr bypassing the need for a web server, allowing it to run in Binder.

**Comment by edwin5588** [comment]
Thanks! I'll try it out. Is this going to be merged into main?
