### ISSUE TITLE
Separate dev dependencies from actual dependencies

### ISSUE THREAD

**Issue by flying-sheep** [vitessce/vitessce-python#376]
`black` should almost certainly not be in `project.dependencies`.

**Comment by keller-mark** [comment]
This is used to construct Jupyter notebooks that contain Python code. The use case is to go from JSON dict to the equivalent Python code block that uses the VitessceConfig API that will generate that same Vitessce configuration

**Comment by keller-mark** [comment]
But would be open to making it optional and imported in the function scope if that is preferred

**Comment by flying-sheep** [comment]
I see, interesting! Sorry for assuming here.
