### ISSUE TITLE
fromDict Should Handle Data Types with no URL

### ISSUE THREAD

**Issue by ilan-gold** [vitessce/vitessce-python#54]
https://github.com/vitessce/vitessce-python/blob/80ba29bf519eaaa47bdedc8f556c63db118bea2b/vitessce/config.py#L713-L721

The above requires that the file object contains a `url` which is not necessarily true, for example, for raster data which have `options` not `url.

**Comment by ilan-gold** [comment]
Needed for (or at least a use case could be made for using this in): https://github.com/hubmapconsortium/portal-ui/tree/ilan-gold/initial_z_stack

**Comment by ngehlenborg** [comment]
Will likely be addressed #115.
