### ISSUE TITLE
Confused about multiple `environment.yaml`: Are both needed?

### ISSUE THREAD

**Issue by mccalluc** [vitessce/vitessce-python#69]
The [README](https://github.com/vitessce/vitessce-python#development) currently says to install the top-level one, but when @keller-mark [set me on the right path](https://github.com/vitessce/vitessce-python/pull/66#issuecomment-854993467) he pointed me at `docs/notebooks/environment.yml`... Should there be two? Either more explanation, or deleting one, may be helpful.

```
diff environment.yml docs/notebooks/environment.yml
1c1
< name: vitessce-jupyter-dev
---
> name: vitessce-jupyter-examples
6c6
<  - python==3.8
---
>  - python>=3.7
9a10,12
>  - numba>=0.53.0
>  - scanpy>=1.6.0
>  - jupyterlab>=3
11,14c14
<  - numcodecs>=0.7.2
<  - scipy>=1.0.0
<  - nbsphinx>=0.7.1
<  - pandoc>=2.11.3
---
>  - boto3>=1.16.30
17d16
<    - build==0.1.0
19,22c18
<    - sphinx
<    - sphinx-rtd-theme
<    - nbclean>=0.3.2
<    - generate-tiff-offsets>=0.1.7
---
>    - scikit-misc>=0.1.3

**Comment by keller-mark** [comment]
The top-level environment is for the development of the `vitessce` package itself.

The inner environment is for running the example notebooks in `docs/notebooks`. The package does not depend on Jupyter or ScanPy, for instance, but running the notebooks does.

We do have a second readme at [`docs/notebooks/README.md`](https://github.com/vitessce/vitessce-python/tree/master/docs/notebooks#readme) but you also have a good point that we should explain this in the main `README.md`
