### ISSUE TITLE
how to vc.widget() in my server

### ISSUE THREAD

**Issue by FADHLyemen** [vitessce/vitessce-python#88]
Hi,
I follow steps in:
https://github.com/vitessce/vitessce-python/blob/master/docs/notebooks/widget_brain.ipynb
when I run on university hpc server using
```
vw=vc.widget()
vw
```
I got `Running on http://127.0.0.1:8002`
and error in chrome:
`This site can’t be reached127.0.0.1 refused to connect.`

Any suggestion how to access the vw?

Thank you

BTW:
I created the following conda env

```
$ git clone https://github.com/vitessce/vitessce-python.git
cd docs/notebooks
conda env create -f environment.yml
conda activate vitessce-jupyter-examples
pip install -e ../..
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install ../../js
```

then 
`jupyter lab
`

**Comment by keller-mark** [comment]
Hi Fadhl,
If you are running the Jupyter server on the HPC and then accessing the widget through visiting the Jupyter client on your personal computer, can you try the following:

1. install the `jupyter-server-proxy` package
2. set the `proxy=True` flag when you run the widget method
    ```
    vw=vc.widget(proxy=True)
    vw
    ```

**Comment by FADHLyemen** [comment]
Thank you, @keller-mark 
I tried it but does not work. 

![image](https://user-images.githubusercontent.com/23288387/126873615-dc166d62-9da7-4465-a43b-2d8985bd7ae3.png)

![image](https://user-images.githubusercontent.com/23288387/126873685-d3102c37-a9f8-4e0b-a202-d7356bb59f20.png)

![image](https://user-images.githubusercontent.com/23288387/126873699-a54b14ac-1085-4191-986d-ca53fa2338e1.png)


I also added 8002 as a tunnel port in puTTy. but still get the same. 

I think there is something wrong. Could you help?

**Comment by FADHLyemen** [comment]
is it because:
Error displaying widget model not found

**Comment by keller-mark** [comment]
I apologize, I think our documentation is missing a step for bundling the JavaScript file for the widget. Can you try:

```
cd js
npm install
npm run build
cd ../docs/notebooks
jupyter labextension install ../../js
```

**Comment by FADHLyemen** [comment]
thank you, 
npm instatll gave me many warrnings
![image](https://user-images.githubusercontent.com/23288387/126883373-5dec66aa-afcd-4dd5-ab5f-b22d532f5c53.png)

npm run build
![image](https://user-images.githubusercontent.com/23288387/126883395-f04ceec3-af97-46bf-8906-595afb234567.png)


BTW I installed nodeJs by
`conda install -c conda-forge nodejs`

**Comment by FADHLyemen** [comment]
@keller-mark any help is appreciated

**Comment by ilan-gold** [comment]
@FADHLyemen What version of `node` and/or `npm` do you have?  Could you provide that debug log file (or a more complete error) - hard to tell what's going on since the screenshot is truncated.  Thanks!

**Comment by ilan-gold** [comment]
@FADHLyemen I see you only have node 6.  @keller-mark can correct me, but I believe you probably need node 14

**Comment by ilan-gold** [comment]
See https://github.com/vitessce/vitessce-python/blob/master/.github/workflows/test.yml for how we set up an example environment in our CI workflow

**Comment by keller-mark** [comment]
Thank you @ilan-gold. Yes, I would also check that you have NodeJS version 14. We should note this in the development section of the README, or point users to the JS repo's README for that step.

Also, I just made this pull request https://github.com/vitessce/vitessce-python/pull/89 which allows using the vitessce.io web app in place of the Jupyter widget, in case you are interested. That would avoid the need to build the JS files locally, (but opens Vitessce in a separate tab rather than embedded in the notebook).

**Comment by FADHLyemen** [comment]
```
$ node -v
v13.13.0
```
BTW:
where is web_app_brain.ipynb to try?

sorry for this, I saw one of your team member presented at ISMB this tool:
http://avivator.gehlenborglab.org/?image_url=https://viv-demo.storage.googleapis.com/LuCa-7color_Scan1

can you do the same for Viteesce, so we only need to upload our h5ad file?

**Comment by ilan-gold** [comment]
@FADHLyemen For Vitessce, we only accept `zarr` backed `AnnData` so an `h5ad` file is similar.  We have considered building wrapper tools around `AnnData` stores (similar to what Avivator does for OME) to make access easier than setting up a view config, but for now it hasn't been something we've focused on.

**Comment by ilan-gold** [comment]
> where is web_app_brain.ipynb to try?
 That is in a PR currently https://github.com/vitessce/vitessce-python/pull/89 and will be merged eventually

**Comment by ilan-gold** [comment]
As for the node version, I would recommend upgrading.  If you could provide that debug log file that NPM is pointing out (`npm-debug.log`) it might also help us to debug with you.

**Comment by FADHLyemen** [comment]
I installed nodejs 14, please see below
![image](https://user-images.githubusercontent.com/23288387/127186670-8fbb358a-29a3-43e9-8b3d-5352dfbcc396.png)

now I run it in jupyter notebook with option proxy =TRUE

![image](https://user-images.githubusercontent.com/23288387/127186553-d426d0ea-c05d-4d3a-a5ff-76323eece970.png)

However can not access 
http://127.0.0.1:8000/
![image](https://user-images.githubusercontent.com/23288387/127186908-8dec6815-5dda-4599-88eb-db0c90cade8d.png)


did I miss any thing?

**Comment by keller-mark** [comment]
This is correct. There is no web page to see at the 127.0.0.1:8000 URL, it is just the hostname of the web server where the raw data is being served from. 

Also, the http://127.0.0.1:8000/ URL is local to the HPC where the Jupyter server is running (rather than your local machine). I will make an issue to change the log message to make it clearer about the context of that URL for the remote/HPC use cases.

**Comment by FADHLyemen** [comment]
you make it easy for me. 
Here what I want to do. I want to put my h5ad file in amazon s3 and visualize the data using vitessce. I want to send our collaborator a link so they can visualize the data without installing any thing at their end.  is this an option in current version of vitessce? could you direct me to do it correctly 
thank you

**Comment by ilan-gold** [comment]
@FADHLyemen Yes that is very doable. We have a [notebook](https://vitessce.github.io/vitessce-python/notebooks/data_export_s3.html) for doing just that, which starts with an `h5ad` file (that you download, so you may simply substitute your own), and then proceeds to set up the vitessce view configuration for it and upload to amazon s3.

**Comment by keller-mark** [comment]
Please see these instructions to make sure that your AWS S3 bucket permissions allow accessing the data on the web http://beta.vitessce.io/docs/data-hosting/index.html#aws-s3

**Comment by FADHLyemen** [comment]
Thank you, how to get the `VITESSCE_S3_ACCESS_KEY_ID.txt` and `VITESSCE_S3_SECRET_ACCESS_KEY.txt`

**Comment by FADHLyemen** [comment]
I got it, 
https://supsystic.com/documentation/id-secret-access-key-amazon-s3/

**Comment by FADHLyemen** [comment]
I still get some error, I appreciate your help
![image](https://user-images.githubusercontent.com/23288387/127237132-00b10f2f-4e31-46b1-a9b4-5efdd21444b5.png)

**Comment by keller-mark** [comment]
You can replace the entire part after the equals sign with the string.

like this: 
```python3
s3 = boto3.resource(
    service_name="s3",
    aws_access_key_id="my_access_key_id",
    aws_secret_access_key="my_secret_access_key"
)
```

**Comment by FADHLyemen** [comment]
when I run
`config_dict = vc.export(to='S3', s3=s3, bucket_name='kidneyscrnaseq')`
I got below error:

boto3.exceptions.S3UploadFailedError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

I read this [[solution]](https://stackoverflow.com/questions/59239977/boto3-exceptions-s3uploadfailederror-an-error-occurred-accessdenied-when-call)

and modify the bucket privacy to:
```
{
    "Version": "2012-10-17",
    "Id": "Policy12345",
    "Statement": [
        {
            "Sid": "Stmt6789",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::kidneyscrnaseq/*"
        }
    ]
}
```

it uploaded successfully. 

now when I run `webbrowser.open`  the cell is busy for long time. I do not know which link to send to  collaborator and how to open the link.  

![image](https://user-images.githubusercontent.com/23288387/127324158-7f6a2d57-6cd1-4139-8c71-d64e1129b9d7.png)

**Comment by ilan-gold** [comment]
The string contents of the "Out[7]" cell are the url you can copy, paste and navigate into a web browser

**Comment by FADHLyemen** [comment]
I just got this for long time, I do not know what is going on:
![image](https://user-images.githubusercontent.com/23288387/127327861-f788b1cd-67b7-4705-9506-0f6f2f55a5b3.png)

**Comment by FADHLyemen** [comment]
Now, it gives this empty page
![image](https://user-images.githubusercontent.com/23288387/127330648-0d6a9517-506c-4ebb-8e93-4d6eeb44bf71.png)

**Comment by ilan-gold** [comment]
@keller-mark I am trying his URL but getting a 403.  Please correct me if I'm wrong @keller-mark but I believe you need to add `s3:ListBucket` to your bucket actions.  I think we had someone else have this problem - I think the documentation has been updated but not redeployed.

**Comment by ilan-gold** [comment]
Also `s3:GetObjectAcl` probably just to be safe....

**Comment by FADHLyemen** [comment]
sorry, I should send you my URL:
http://vitessce.io/?url=data:,%7B%22version%22%3A+%221.0.2%22%2C+%22name%22%3A+%22Habib+et+al%22%2C+%22description%22%3A+%22COVID-19+Healthy+Donor+Brain%22%2C+%22datasets%22%3A+%5B%7B%22uid%22%3A+%22A%22%2C+%22name%22%3A+%22Brain%22%2C+%22files%22%3A+%5B%7B%22type%22%3A+%22cells%22%2C+%22fileType%22%3A+%22anndata-cells.zarr%22%2C+%22url%22%3A+%22https%3A%2F%2Fkidneyscrnaseq.s3.amazonaws.com%2FA%2F0%2Fanndata.zarr%22%2C+%22options%22%3A+%7B%22mappings%22%3A+%7B%22UMAP%22%3A+%7B%22key%22%3A+%22obsm%2FX_umap%22%2C+%22dims%22%3A+%5B0%2C+1%5D%7D%7D%7D%7D%2C+%7B%22type%22%3A+%22cell-sets%22%2C+%22fileType%22%3A+%22anndata-cell-sets.zarr%22%2C+%22url%22%3A+%22https%3A%2F%2Fkidneyscrnaseq.s3.amazonaws.com%2FA%2F0%2Fanndata.zarr%22%2C+%22options%22%3A+%5B%7B%22groupName%22%3A+%22Cell+Type%22%2C+%22setName%22%3A+%22obs%2FCellType%22%7D%5D%7D%2C+%7B%22type%22%3A+%22expression-matrix%22%2C+%22fileType%22%3A+%22anndata-expression-matrix.zarr%22%2C+%22url%22%3A+%22https%3A%2F%2Fkidneyscrnaseq.s3.amazonaws.com%2FA%2F0%2Fanndata.zarr%22%2C+%22options%22%3A+%7B%22matrix%22%3A+%22X%22%2C+%22matrixGeneFilter%22%3A+%22var%2Ftop_highly_variable%22%7D%7D%5D%7D%5D%2C+%22coordinationSpace%22%3A+%7B%22dataset%22%3A+%7B%22A%22%3A+%22A%22%7D%2C+%22embeddingType%22%3A+%7B%22A%22%3A+%22X_umap%22%7D%7D%2C+%22layout%22%3A+%5B%7B%22component%22%3A+%22scatterplot%22%2C+%22coordinationScopes%22%3A+%7B%22dataset%22%3A+%22A%22%2C+%22embeddingType%22%3A+%22A%22%7D%2C+%22x%22%3A+0.0%2C+%22y%22%3A+0.0%2C+%22w%22%3A+6.0%2C+%22h%22%3A+6.0%7D%2C+%7B%22component%22%3A+%22cellSets%22%2C+%22coordinationScopes%22%3A+%7B%22dataset%22%3A+%22A%22%7D%2C+%22x%22%3A+6.0%2C+%22y%22%3A+0.0%2C+%22w%22%3A+6.0%2C+%22h%22%3A+3.0%7D%2C+%7B%22component%22%3A+%22genes%22%2C+%22coordinationScopes%22%3A+%7B%22dataset%22%3A+%22A%22%7D%2C+%22x%22%3A+6.0%2C+%22y%22%3A+3.0%2C+%22w%22%3A+6.0%2C+%22h%22%3A+3.0%7D%2C+%7B%22component%22%3A+%22heatmap%22%2C+%22coordinationScopes%22%3A+%7B%22dataset%22%3A+%22A%22%7D%2C+%22x%22%3A+0%2C+%22y%22%3A+6.0%2C+%22w%22%3A+12%2C+%22h%22%3A+6.0%7D%5D%2C+%22initStrategy%22%3A+%22auto%22%7D

**Comment by keller-mark** [comment]
Yes, sorry I thought it had been re-deployed.

https://github.com/vitessce/vitessce/blob/keller-mark/docs/docs/docs/data-hosting.md#bucket-policy

```
{
  "Version": "2012-10-17",
  "Id": "Policy12345",
  "Statement": [
    {
      "Sid": "Stmt6789",
      "Effect": "Allow",
      "Principal": "*",
      "Action": [
        "s3:GetObject",
        "s3:GetObjectAcl",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::foo-bar",
        "arn:aws:s3:::foo-bar/*"
      ]
    }
  ]
}
```

**Comment by FADHLyemen** [comment]
@keller-mark if I did not include s3:PutObject" in action, I got access denied. 
so below is my bucket policy 

{
    "Version": "2012-10-17",
    "Id": "Policy12345",
    "Statement": [
        {
            "Sid": "Stmt6789",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:ListBucket",
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::kidneyscrnaseq",
                "arn:aws:s3:::kidneyscrnaseq/*"
            ]
        }
    ]
}


I rerun 

```
s3 = boto3.resource(
    service_name='s3',
    aws_access_key_id='my code',
    aws_secret_access_key='my secret code',
)
config_dict = vc.export(to='S3', s3=s3, bucket_name='kidneyscrnaseq')

vitessce_url = "http://vitessce.io/?url=data:," + quote_plus(json.dumps(config_dict))
```
vitessce_url is 

http://vitessce.io/?url=data:,%7B%22version%22%3A+%221.0.2%22%2C+%22name%22%3A+%22Habib+et+al%22%2C+%22description%22%3A+%22COVID-19+Healthy+Donor+Brain%22%2C+%22datasets%22%3A+%5B%7B%22uid%22%3A+%22A%22%2C+%22name%22%3A+%22Brain%22%2C+%22files%22%3A+%5B%7B%22type%22%3A+%22cells%22%2C+%22fileType%22%3A+%22anndata-cells.zarr%22%2C+%22url%22%3A+%22https%3A%2F%2Fkidneyscrnaseq.s3.amazonaws.com%2FA%2F0%2Fanndata.zarr%22%2C+%22options%22%3A+%7B%22mappings%22%3A+%7B%22UMAP%22%3A+%7B%22key%22%3A+%22obsm%2FX_umap%22%2C+%22dims%22%3A+%5B0%2C+1%5D%7D%7D%7D%7D%2C+%7B%22type%22%3A+%22cell-sets%22%2C+%22fileType%22%3A+%22anndata-cell-sets.zarr%22%2C+%22url%22%3A+%22https%3A%2F%2Fkidneyscrnaseq.s3.amazonaws.com%2FA%2F0%2Fanndata.zarr%22%2C+%22options%22%3A+%5B%7B%22groupName%22%3A+%22Cell+Type%22%2C+%22setName%22%3A+%22obs%2FCellType%22%7D%5D%7D%2C+%7B%22type%22%3A+%22expression-matrix%22%2C+%22fileType%22%3A+%22anndata-expression-matrix.zarr%22%2C+%22url%22%3A+%22https%3A%2F%2Fkidneyscrnaseq.s3.amazonaws.com%2FA%2F0%2Fanndata.zarr%22%2C+%22options%22%3A+%7B%22matrix%22%3A+%22X%22%2C+%22matrixGeneFilter%22%3A+%22var%2Ftop_highly_variable%22%7D%7D%5D%7D%5D%2C+%22coordinationSpace%22%3A+%7B%22dataset%22%3A+%7B%22A%22%3A+%22A%22%7D%2C+%22embeddingType%22%3A+%7B%22A%22%3A+%22X_umap%22%7D%7D%2C+%22layout%22%3A+%5B%7B%22component%22%3A+%22scatterplot%22%2C+%22coordinationScopes%22%3A+%7B%22dataset%22%3A+%22A%22%2C+%22embeddingType%22%3A+%22A%22%7D%2C+%22x%22%3A+0.0%2C+%22y%22%3A+0.0%2C+%22w%22%3A+6.0%2C+%22h%22%3A+6.0%7D%2C+%7B%22component%22%3A+%22cellSets%22%2C+%22coordinationScopes%22%3A+%7B%22dataset%22%3A+%22A%22%7D%2C+%22x%22%3A+6.0%2C+%22y%22%3A+0.0%2C+%22w%22%3A+6.0%2C+%22h%22%3A+3.0%7D%2C+%7B%22component%22%3A+%22genes%22%2C+%22coordinationScopes%22%3A+%7B%22dataset%22%3A+%22A%22%7D%2C+%22x%22%3A+6.0%2C+%22y%22%3A+3.0%2C+%22w%22%3A+6.0%2C+%22h%22%3A+3.0%7D%2C+%7B%22component%22%3A+%22heatmap%22%2C+%22coordinationScopes%22%3A+%7B%22dataset%22%3A+%22A%22%7D%2C+%22x%22%3A+0%2C+%22y%22%3A+6.0%2C+%22w%22%3A+12%2C+%22h%22%3A+6.0%7D%5D%2C+%22initStrategy%22%3A+%22auto%22%7D


which is still not working. did I miss any thing?

**Comment by ilan-gold** [comment]
In your view config, you have 
```json
"embeddingType": {
   "A": "X_umap"
}
```
which should be 
```json
"embeddingType": {
   "A": "UMAP"
}
```
because your `anndata-cells` loader looks like:
```json
{
  "type": "cells",
  "fileType": "anndata-cells.zarr",
  "url": "https://kidneyscrnaseq.s3.amazonaws.com/A/0/anndata.zarr",
  "options": {
    "mappings": {
      "UMAP": {
        "key": "obsm/X_umap",
        "dims": [
          0,
          1
        ]
      }
    }
  }
}
```
i.e the mapping needs to match the `embeddingType`.

It looks like this is a bug in [our example](https://vitessce.github.io/vitessce-python/notebooks/data_export_s3.html#3.-Create-the-Vitessce-configuration) that you followed.  So replace
```python
scatterplot = vc.add_view(dataset, cm.SCATTERPLOT, mapping="X_umap")
```
with
```python
scatterplot = vc.add_view(dataset, cm.SCATTERPLOT, mapping="UMAP")
```

Once I fix that I am able to see your dataset - sorry about that!

**Comment by FADHLyemen** [comment]
Wow, it works, thank you @keller-mark and @ilan-gold for your patience. 
I have two things. first this is a very long link, any suggestion to short it? second, do you have example of vitessce with umap for scrna-seq and image. I can not find this in your example. how to connect the h5ad with the image coordinates. thank you again


http://vitessce.io/?url=data:,%7B%22version%22%3A+%221.0.2%22%2C+%22name%22%3A+%22Habib+et+al%22%2C+%22description%22%3A+%22COVID-19+Healthy+Donor+Brain%22%2C+%22datasets%22%3A+%5B%7B%22uid%22%3A+%22A%22%2C+%22name%22%3A+%22Brain%22%2C+%22files%22%3A+%5B%7B%22type%22%3A+%22cells%22%2C+%22fileType%22%3A+%22anndata-cells.zarr%22%2C+%22url%22%3A+%22https%3A%2F%2Fkidneyscrnaseq.s3.amazonaws.com%2FA%2F0%2Fanndata.zarr%22%2C+%22options%22%3A+%7B%22mappings%22%3A+%7B%22UMAP%22%3A+%7B%22key%22%3A+%22obsm%2FX_umap%22%2C+%22dims%22%3A+%5B0%2C+1%5D%7D%7D%7D%7D%2C+%7B%22type%22%3A+%22cell-sets%22%2C+%22fileType%22%3A+%22anndata-cell-sets.zarr%22%2C+%22url%22%3A+%22https%3A%2F%2Fkidneyscrnaseq.s3.amazonaws.com%2FA%2F0%2Fanndata.zarr%22%2C+%22options%22%3A+%5B%7B%22groupName%22%3A+%22Cell+Type%22%2C+%22setName%22%3A+%22obs%2FCellType%22%7D%5D%7D%2C+%7B%22type%22%3A+%22expression-matrix%22%2C+%22fileType%22%3A+%22anndata-expression-matrix.zarr%22%2C+%22url%22%3A+%22https%3A%2F%2Fkidneyscrnaseq.s3.amazonaws.com%2FA%2F0%2Fanndata.zarr%22%2C+%22options%22%3A+%7B%22matrix%22%3A+%22X%22%2C+%22matrixGeneFilter%22%3A+%22var%2Ftop_highly_variable%22%7D%7D%5D%7D%5D%2C+%22coordinationSpace%22%3A+%7B%22dataset%22%3A+%7B%22A%22%3A+%22A%22%7D%2C+%22embeddingType%22%3A+%7B%22A%22%3A+%22UMAP%22%7D%7D%2C+%22layout%22%3A+%5B%7B%22component%22%3A+%22scatterplot%22%2C+%22coordinationScopes%22%3A+%7B%22dataset%22%3A+%22A%22%2C+%22embeddingType%22%3A+%22A%22%7D%2C+%22x%22%3A+0.0%2C+%22y%22%3A+0.0%2C+%22w%22%3A+6.0%2C+%22h%22%3A+6.0%7D%2C+%7B%22component%22%3A+%22cellSets%22%2C+%22coordinationScopes%22%3A+%7B%22dataset%22%3A+%22A%22%7D%2C+%22x%22%3A+6.0%2C+%22y%22%3A+0.0%2C+%22w%22%3A+6.0%2C+%22h%22%3A+3.0%7D%2C+%7B%22component%22%3A+%22genes%22%2C+%22coordinationScopes%22%3A+%7B%22dataset%22%3A+%22A%22%7D%2C+%22x%22%3A+6.0%2C+%22y%22%3A+3.0%2C+%22w%22%3A+6.0%2C+%22h%22%3A+3.0%7D%2C+%7B%22component%22%3A+%22heatmap%22%2C+%22coordinationScopes%22%3A+%7B%22dataset%22%3A+%22A%22%7D%2C+%22x%22%3A+0%2C+%22y%22%3A+6.0%2C+%22w%22%3A+12%2C+%22h%22%3A+6.0%7D%5D%2C+%22initStrategy%22%3A+%22auto%22%7D

**Comment by ilan-gold** [comment]
@FADHLyemen Yes it is completely possible.  Perhaps you can open a [discussion}(https://github.com/vitessce/vitessce-python/discussions) for this new issue and we can resolve the issue there - especially if you have any data to share, I'd be happy to create an example notebook as this seems to be an increasingly common request.

**Comment by ilan-gold** [comment]
As for the URL length, you can use a URL shorten-er like [tinyurl](https://tinyurl.com/app/myurls)

**Comment by ilan-gold** [comment]
In the meantime I am going to close this issue @FADHLyemen but please do open a discussion post!
